# Generated by Django 5.2.8 on 2025-11-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyusage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScheduledPriceChange',
        ),
        migrations.DeleteModel(
            name='WeeklyUsage',
        ),
    ]
