# Generated by Django 5.2.8 on 2025-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_weekly_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('unlimited', 'Unlimited')], default='free', max_length=20, unique=True),
        ),
    ]
