# Generated by Django 5.2.8 on 2025-11-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='summary',
            new_name='summarized',
        ),
    ]
