# Generated by Django 5.2.8 on 2025-11-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_rename_summary_note_summarized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='summarized',
            field=models.TextField(blank=True),
        ),
    ]
