# Generated by Django 5.2.8 on 2025-11-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_note_summarized'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
