# Generated by Django 5.2.8 on 2025-12-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_note_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_datetime']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
