# Generated by Django 5.2.8 on 2025-12-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_alter_event_options_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
