# Generated by Django 5.2.8 on 2025-12-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_alter_event_options_remove_event_event_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_datetime']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(blank=True, help_text='Event date and time in UTC (ISO 8601 format)', null=True),
        ),
    ]
