# Generated by Django 5.2.8 on 2025-12-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_bot_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable WhatsApp bot integration'),
        ),
    ]
